### ISSUE TITLE
[Bug] Session joining after the quiz finished

### ISSUE THREAD

**Issue by andrewjunggg** [BetterAttendance/BetterAttendance-Frontend#21]
**Describe the bug**
Whenever the session is finished, another attendee can join the session page on the finished session.

**To Reproduce**
1. Join any finished session

**Expected behavior**
We should reject the user joining with a message that the session has finished.

**Screenshots**
![image](https://github.com/BetterAttendance/BetterAttendance-Frontend/assets/20850823/06bcd1a7-41d6-473c-902a-28077253a5da)

**Comment by khois345** [comment]
Already done in quiz-object-creation branch

**Comment by khois345** [comment]
Already done in quiz-object-creation branch
