### ISSUE TITLE
[Bug] User join while the session is running pop up is not showing the correct message

### ISSUE THREAD

**Issue by andrewjunggg** [BetterAttendance/BetterAttendance-Frontend#22]
**Describe the bug**
User join while the session is running pop up is not showing the correct message

**To Reproduce**
Join a running session as an attendee

**Expected behavior**
The message should indicate that the session is currently running, and joining is not available.

**Screenshots**
![image](https://github.com/BetterAttendance/BetterAttendance-Frontend/assets/20850823/e728811c-5a45-475a-965c-ba83efca5b7d)

**Comment by khois345** [comment]
Already done in quiz-object-creation branch

**Comment by khois345** [comment]
Already done in quiz-object-creation branch
